### PR TITLE
TabletBot rewrite to poise

### LINKED ISSUE #18: Edit-embed command
All current embeds cannot be modified after their creation, a command could be added to edit embeds.

### LINKED ISSUE #19: /embed command doesn't parse newlines
image

### LINKED ISSUE #21: Feature Request: Link to other projects than the main project (issue prefix token?)
Would be nice to use e.g. `web#25` to link to the equivalent issue (in this case OpenTabletDriver/opentabletdriver.github.io#112)

Being able to add which tokens are available on runtime would be preferable, e.g. `/addissuetoken web OpenTabletDriver.Web` though obviously only for privileged users.

### LINKED ISSUE #22: "Hide body" feature
When generating PR previews (as attached), it would be nice if there was a optional feature to remove the body of the issue so that it doesn't fill up the chat quite as significantly. I've attached an example of how it would look.

Before:
image

After:
image

In other Discord bots this is usually enabled by having interactive buttons beneath the message (which also usually disappear after a couple of minutes)

### PR DESCRIPTION
**Pull request by jamesbt365**
This pull request fixes:
- Fixes #18 
- Fixes #19 
- Fixes #21 
- Fixes #22

Stuff left to complete in this pull request:
- [x] Restore Embed Command (and fix it because broken on current TabletBot)
- [x] Fix code snippet posting (broke it on purpose to satisfy the compiler while I was rewriting)
- [x] restore and fix edit-snippets (broken on original bot)
- [x] Pin to 0.12 serenity when new poise release drops.
- [x] Add `track_edits` to commands
- [x] Fix workflow

A lot has changed in serenity since this bot was written, and I decided to go ahead and do a rewrite into poise to allow for more flexibility in commands.

poise allows for hybrid command support which we are using here to restore prefix commands.

Poise however does not allow for getting mutable references to custom data, so snippets now have to be in a synchronization primitive.

Previously commands were accessible in DMs, allowing for anybody to go into DMs and modify snippets regardless of permissions.

Because TabletBot is designed for one guild I haven't locked down the commands to permissions, but I have disabled the commands in DMs in this pull request to prevent this abuse from happening. Permissions will continue to be locked down in the OpenTabletDriver guild.

### CODE REVIEW

**Comment by jamesbt365** [comment]
Other than fixing the workflow it should work just fine.

**Comment by jamesbt365** [comment]
Not even sure how the workflow works or what needs changing but I'll look into it.

**Comment by jamesbt365** [comment]
I have gone ahead and pushed a new flake simply to fix the workflow (it needed newer rust and nix unstable didn't have it).

This probably isn't the best way to do it, as well as it no longer includes the dev shell or the default.nix file. I would prefer if somebody else came up with a proper solution but at this moment I don't have the energy to figure out a better way of doing it.

**Comment by InfinityGhost** [comment]
This pr is big enough, and we've already deployed some revisions of it so I figure we can go ahead and merge this.

**Review by InfinityGhost — APPROVED** [review]

**Pull request merged**
